### ISSUE TITLE
Error OSError: [Errno 5] Input/output error | when i try manually run `server.py` or `webServer.py`.

### ISSUE THREAD

**Issue by PhanTrongGiap** [adeept/Adeept_RaspClaws#1]
python3 Adeept_RaspClaws/server/webServer.py
Traceback (most recent call last):
  File "/home/admin/Adeept_RaspClaws/server/webServer.py", line 10, in <module>
    import move
  File "/home/admin/Adeept_RaspClaws/server/move.py", line 14, in <module>
    import RPIservo
  File "/home/admin/Adeept_RaspClaws/server/RPIservo.py", line 17, in <module>
    pwm = Adafruit_PCA9685.PCA9685()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/robot/lib/python3.11/site-packages/Adafruit_PCA9685/PCA9685.py", line 75, in __init__
    self.set_all_pwm(0, 0)
  File "/home/admin/robot/lib/python3.11/site-packages/Adafruit_PCA9685/PCA9685.py", line 111, in set_all_pwm
    self._device.write8(ALL_LED_ON_L, on & 0xFF)
  File "/home/admin/robot/lib/python3.11/site-packages/Adafruit_GPIO/I2C.py", line 114, in write8
    self._bus.write_byte_data(self._address, register, value)
  File "/home/admin/robot/lib/python3.11/site-packages/Adafruit_PureIO/smbus.py", line 316, in write_byte_data
    self._device.write(data)
OSError: [Errno 5] Input/output error

**Comment by adeept** [comment]
Hello,
It may be caused by incompatibility between the Raspberry Pi image file and some dependent libraries.
Please download and burn Raspberry Pi OS (Legacy) according to the content "Method one" in the link below, then configure SSH and WiFi, download the product code and run the setup.py program.
Link：https://www.adeept.com/learn/tutorial-160.html


Best!


 Technical Support
 ***@***.***
  



---- Replied Message ----
From  Phan Trong ***@***.***> Date  11/5/2023 03:39 To  ***@***.***> Cc  ***@***.***> Subject  [adeept/Adeept_RaspClaws] Error OSError: [Errno 5] Input/output error | when i try manually run `server.py` or `webServer.py`. (Issue #1)  

python3 Adeept_RaspClaws/server/webServer.py
 Traceback (most recent call last):
 File "/home/admin/Adeept_RaspClaws/server/webServer.py", line 10, in
 import move
 File "/home/admin/Adeept_RaspClaws/server/move.py", line 14, in
 import RPIservo
 File "/home/admin/Adeept_RaspClaws/server/RPIservo.py", line 17, in
 pwm = Adafruit_PCA9685.PCA9685()
 ^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/home/admin/robot/lib/python3.11/site-packages/Adafruit_PCA9685/PCA9685.py", line 75, in init
 self.set_all_pwm(0, 0)
 File "/home/admin/robot/lib/python3.11/site-packages/Adafruit_PCA9685/PCA9685.py", line 111, in set_all_pwm
 self._device.write8(ALL_LED_ON_L, on & 0xFF)
 File "/home/admin/robot/lib/python3.11/site-packages/Adafruit_GPIO/I2C.py", line 114, in write8
 self._bus.write_byte_data(self._address, register, value)
 File "/home/admin/robot/lib/python3.11/site-packages/Adafruit_PureIO/smbus.py", line 316, in write_byte_data
 self._device.write(data)
 OSError: [Errno 5] Input/output error

**Comment by PhanTrongGiap** [comment]
我已经安装并遵循了大约15次。我已经阅读了您的所有文档。
我遵循了所有3个方法，仍然是同样的错误

**Comment by adeept** [comment]
Hello,
1. Please confirm whether the HAT expansion board is installed correctly.
2. Please confirm whether I2C is turned on. Open the steps and enter: in the Raspberry Pi command line:
sudo raspi-config
Select "3 Interface options"
Select "P5 I2C"
Select "Yes" to open i2c


3. Run the command "i2cdetect -y 1" to check the address occupancy. After the HAT expansion board is correctly installed, it will occupy the two addresses "0x40" and "0x70".


Best!


 Technical Support
 ***@***.***
  



---- Replied Message ----
From  Phan Trong ***@***.***> Date  11/6/2023 21:23 To  ***@***.***> Cc  ***@***.***> ,
 ***@***.***> Subject  Re: [adeept/Adeept_RaspClaws] Error OSError: [Errno 5] Input/output error | when i try manually run `server.py` or `webServer.py`. (Issue #1)  

我已经安装并遵循了大约15次。我已经阅读了您的所有文档。
 我遵循了所有3个方法，仍然是同样的错误

**Comment by adeept** [comment]
In addition, after installing the Raspberry Pi image file we recommend, the python version in the Raspberry Pi is 3.7


 Technical Support
 ***@***.***
  



---- Replied Message ----
From  Phan Trong ***@***.***> Date  11/6/2023 21:23 To  ***@***.***> Cc  ***@***.***> ,
 ***@***.***> Subject  Re: [adeept/Adeept_RaspClaws] Error OSError: [Errno 5] Input/output error | when i try manually run `server.py` or `webServer.py`. (Issue #1)  

我已经安装并遵循了大约15次。我已经阅读了您的所有文档。
 我遵循了所有3个方法，仍然是同样的错误
