### ISSUE TITLE
Error on WebServer.py start AttributeError: 'NoneType' object has no attribute 'all'`

### ISSUE THREAD

**Issue by MatzGer** [adeept/Adeept_RaspClaws#2]
I'm trying to install my RaspClaws. I have installed the SD-Card according to Method 1 (Legacy, with Desktop and recommended Software). SSH und Wifi works and I already installed with setup.py.

The first error was:
`pi@raspberrypi:~ $ sudo python3 adeept_raspclaws/server/webServer.py
mpu6050 connected, PT MODE ON
Traceback (most recent call last):
  File "/home/pi/adeept_raspclaws/server/webServer.py", line 25, in <module>
    import app
  File "/home/pi/adeept_raspclaws/server/app.py", line 8, in <module>
    from camera_opencv import Camera
  File "/home/pi/adeept_raspclaws/server/camera_opencv.py", line 12, in <module>
    import imutils
ModuleNotFoundError: No module named 'imutils'`

This was solved by "sudo pip install --upgrade imutils"

Now I can't continue as the servo won't move as the WebServer won't start correct:

`Starting camera thread.
[ WARN:0] global ../modules/videoio/src/cap_gstreamer.cpp (1824) handleMessage OpenCV | GStreamer warning: Embedded video playback halted; module v4l2src0 reported: Failed to allocate required memory.
[ WARN:0] global ../modules/videoio/src/cap_gstreamer.cpp (914) open OpenCV | GStreamer warning: unable to start pipeline
[ WARN:0] global ../modules/videoio/src/cap_gstreamer.cpp (501) isPipelinePlaying OpenCV | GStreamer warning: GStreamer: pipeline have not been created
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/adeept_raspclaws/server/base_camera.py", line 94, in _thread
    for frame in frames_iterator:
  File "/home/pi/adeept_raspclaws/server/camera_opencv.py", line 421, in frames
    if img.all is None:
AttributeError: 'NoneType' object has no attribute 'all'`

**Comment by adeept** [comment]
Hello,

1. Enter: sudo killall python3 in the Raspberry Pi command line
2. Enter the command: "raspistill - t 1000- o image. jpg". Normally, the Raspberry Pi will take an image. jpg photo, which can be viewed through "ls". If there is an error during operation, please check if the camera is installed correctly. The camera can be removed and reinstalled. Until the photo is successfully taken


Turn on the camera
sudo raspi-config
Select '3 Interface Options'
Select 'I1 Legacy Camera'
Select 'Yes' to turn on the camera




Best!
------------------------------------------
Adeept Tech Support Team
Adeept Technology Co., Ltd.
E-mail: ***@***.***
Web: www.adeept.com










---- Replied Message ----
From ***@***.***> Date 12/27/2024 23:51 To ***@***.***> Cc ***@***.***> Subject [adeept/Adeept_RaspClaws] Error on WebServer.py start AttributeError: 'NoneType' object has no attribute 'all'` (Issue #2)  
I'm trying to install my RaspClaws. I have installed the SD-Card according to Method 1 (Legacy, with Desktop and recommended Software). SSH und Wifi works and I already installed with setup.py.
The first error was:
 ***@***.***:~ $ sudo python3 adeept_raspclaws/server/webServer.py mpu6050 connected, PT MODE ON Traceback (most recent call last): File "/home/pi/adeept_raspclaws/server/webServer.py", line 25, in <module> import app File "/home/pi/adeept_raspclaws/server/app.py", line 8, in <module> from camera_opencv import Camera File "/home/pi/adeept_raspclaws/server/camera_opencv.py", line 12, in <module> import imutils ModuleNotFoundError: No module named 'imutils'
This was solved by "sudo pip install --upgrade imutils"
Now I can't continue as the servo won't move as the WebServer won't start correct:
Starting camera thread. [ WARN:0] global ../modules/videoio/src/cap_gstreamer.cpp (1824) handleMessage OpenCV | GStreamer warning: Embedded video playback halted; module v4l2src0 reported: Failed to allocate required memory. [ WARN:0] global ../modules/videoio/src/cap_gstreamer.cpp (914) open OpenCV | GStreamer warning: unable to start pipeline [ WARN:0] global ../modules/videoio/src/cap_gstreamer.cpp (501) isPipelinePlaying OpenCV | GStreamer warning: GStreamer: pipeline have not been created Exception in thread Thread-5: Traceback (most recent call last): File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner self.run() File "/usr/lib/python3.9/threading.py", line 892, in run self._target(*self._args, **self._kwargs) File "/home/pi/adeept_raspclaws/server/base_camera.py", line 94, in _thread for frame in frames_iterator: File "/home/pi/adeept_raspclaws/server/camera_opencv.py", line 421, in frames if img.all is None: AttributeError: 'NoneType' object has no attribute 'all'

**Comment by MatzGer** [comment]
Hi, thanks for your fast answer. Unfortunately I don't think this error is because of the camera installation.
I have reinstalled with legacy raspbian according to your tutorial (Raspberry Pi old version image file (2021-5-07)). I also had to "sudo pip install --upgrade imutils" because of the first error but after this step it seems to work now.

Would be nice if we could use current raspbian image tho.

**Comment by Hyzz8** [comment]
YO IGUAL SIGO CON EL PROBLEMA Y NO SE OBTIENE ARCHIVOS ACTUALIZADOS

**Comment by Hyzz8** [comment]
NO FUNCIONA

**Comment by adeept** [comment]
Hello,

Sorry, based on your current issue and the information provided, I am unable to confirm what your specific problem is and provide a solution.
Can you send me a screenshot of the error message on the terminal so that I can analyze the specific problem you are facing.


Best!
------------------------------------------
Adeept Tech Support Team
Adeept Technology Co., Ltd.
E-mail: ***@***.***
Web: www.adeept.com










---- Replied Message ----
From ***@***.***> Date 1/15/2025 23:27 To ***@***.***> Cc ***@***.***>,
***@***.***> Subject Re: [adeept/Adeept_RaspClaws] Error on WebServer.py start AttributeError: 'NoneType' object has no attribute 'all'` (Issue #2)  
NO FUNCIONA
